// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/regiones": {
    params: {};
  };
  "/regiones/:regionSlug/:comunaToken": {
    params: {
      "regionSlug": string;
      "comunaToken": string;
    };
  };
  "/regiones/:slug": {
    params: {
      "slug": string;
    };
  };
  "/quienes-somos": {
    params: {};
  };
  "/contacto": {
    params: {};
  };
  "/politica-de-privacidad": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/regiones" | "/regiones/:regionSlug/:comunaToken" | "/regiones/:slug" | "/quienes-somos" | "/contacto" | "/politica-de-privacidad" | "/*";
  };
  "pages/Home.jsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/Regiones.jsx": {
    id: "pages/Regiones";
    page: "/regiones";
  };
  "pages/ComunaPage.jsx": {
    id: "pages/ComunaPage";
    page: "/regiones/:regionSlug/:comunaToken";
  };
  "pages/RegionPage.jsx": {
    id: "pages/RegionPage";
    page: "/regiones/:slug";
  };
  "pages/QuienesSomos.jsx": {
    id: "pages/QuienesSomos";
    page: "/quienes-somos";
  };
  "pages/Contacto.jsx": {
    id: "pages/Contacto";
    page: "/contacto";
  };
  "pages/PoliticaPrivacidad.jsx": {
    id: "pages/PoliticaPrivacidad";
    page: "/politica-de-privacidad";
  };
  "pages/NotFound.jsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/Home": typeof import("./src/pages/Home.jsx");
  "pages/Regiones": typeof import("./src/pages/Regiones.jsx");
  "pages/ComunaPage": typeof import("./src/pages/ComunaPage.jsx");
  "pages/RegionPage": typeof import("./src/pages/RegionPage.jsx");
  "pages/QuienesSomos": typeof import("./src/pages/QuienesSomos.jsx");
  "pages/Contacto": typeof import("./src/pages/Contacto.jsx");
  "pages/PoliticaPrivacidad": typeof import("./src/pages/PoliticaPrivacidad.jsx");
  "pages/NotFound": typeof import("./src/pages/NotFound.jsx");
};