export const REGIONES = [
  { id: 15, nombre: "Región de Arica y Parinacota (XV)", imagen: "/img/Arica-y-Parinacota.webp" },
  { id: 1,  nombre: "Región de Tarapacá (I)", imagen: "/img/Tarapaca.webp" },
  { id: 2,  nombre: "Región de Antofagasta (II)", imagen: "/img/Antofagasta.webp" },
  { id: 3,  nombre: "Región de Atacama (III)", imagen: "/img/Atacama.webp" },
  { id: 4,  nombre: "Región de Coquimbo (IV)", imagen: "/img/Coquimbo.webp" },
  { id: 5,  nombre: "Región de Valparaíso (V)", imagen: "/img/Valparaiso.webp" },
  { id: 13, nombre: "Región Metropolitana de Santiago (RM)", imagen: "/img/Santiago.webp" },
  { id: 6,  nombre: "Región del Libertador General Bernardo O'Higgins (VI)", imagen: "/img/Ohiggins.webp" },
  { id: 7,  nombre: "Región del Maule (VII)", imagen: "/img/Maule.webp" },
  { id: 16, nombre: "Región de Ñuble (XVI)", imagen: "/img/Nuble.webp" },
  { id: 8,  nombre: "Región del Biobío (VIII)", imagen: "/img/Biobio.webp" },
  { id: 9,  nombre: "Región de La Araucanía (IX)", imagen: "/img/Araucania.webp" },
  { id: 14, nombre: "Región de Los Ríos (XIV)", imagen: "/img/Rios.webp" },
  { id: 10, nombre: "Región de Los Lagos (X)", imagen: "/img/Lagos.webp" },
  { id: 11, nombre: "Región de Aysén del General Carlos Ibáñez del Campo (XI)", imagen: "/img/Aysen.webp" },
  { id: 12, nombre: "Región de Magallanes y de la Antártica Chilena (XII)", imagen: "/img/Magallanes.webp" },
];
